# Print out all phrases and regex to be filtered out on startup
# default: true
printOnStart = true
# Print a single line on start saying that Clean Logs will filter from this point forward
# default: false
printInitLineOnStart = false
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["true", "false"]
# If a log message matches one of these regex patterns, it will be filtered out from logging
regex = []

