# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				pig = true
				allay = true
				skeleton = true
				bat = true
				frog = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				goat = true
				horse = true
				phantom = true
				minecart = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				donkey = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				blaze = true
				cat = true
				zombie = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				villager = true
				wolf = true
				skeleton_horse = true
				zombie_villager = true
				chest_boat = true
				boat = true
				polar_bear = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.blasttravel]
				cannon = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				super_glue = true

			[light_sources.settings.entities.whipdashing]
				hook_entity = true

			[light_sources.settings.entities.ad_astra]
				ice_spit = true
				martian_raptor = true
				corrupted_lunarian = true
				lunarian = true
				tier_1_rover = true
				tier_4_rocket = true
				star_crawler = true
				lander = true

